{% set version = "0.3.0" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://github.com/pyviz/panel/archive/v{{ version }}.tar.gz
  sha256: 48debc60f06ef2940fb10a5412c3c61bcec3a069961440221690cfe86059e7f9

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
    - param >=1.8.1
  run:
    - bokeh >=0.12.15
    - param >=1.8.1
    - pyviz_comms >=0.6.0
    - markdown
    - testpath <0.4

test:
  imports:
    - panel

about:
  home: https://panel.pyviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
