{% set version = "1.0.4" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 407d21ba6de58543730056d015ebe9acd41e51880783986df43fc170ff9f0cce

build:
  number: 0
  noarch: python
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    # These are also needed at build time.
    - bleach
    - bokeh >=3.1.1,<3.2
    - nodejs >=10.13.0
    - packaging
    - param >=1.9.0
    - pyct >=0.4.4
    - pyviz_comms >=0.7.4
    - requests
    - tqdm >=4.48.0
  run:
    - python >=3.8
    - bleach
    - packaging
    - bokeh >=3.1.1,<3.2
    - markdown
    - param >=1.12.0,<3
    - pyviz_comms >=0.7.4
    - requests
    - tqdm >=4.48.0
    - typing_extensions
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
  run_constrained:
    - holoviews >=1.16.0

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python.
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
    - maximlt
