{% set version = "1.5.2" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 30a45f314716bdde2de5c002fbd3a0b4d6ff85459e2179284df559455ff1534b

build:
  number: 0
  noarch: python
  entry_points:
    - panel = panel.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - nodejs >=18
    # These are also needed at build time.
    - hatchling
    - hatch-vcs
    - param >=2.1.0
    - bokeh >=3.5.0,<3.7.0
    - pyviz_comms >=0.7.4
    - requests
    - packaging
  run:
    - python >=3.10
    - bokeh >=3.5.0,<3.7.0
    - param >=2.1.0,<3.0
    - pyviz_comms >=2.0.0
    - markdown
    - markdown-it-py
    - linkify-it-py
    - mdit-py-plugins
    - requests
    - bleach
    - typing_extensions
    - pandas >=1.2
    - packaging
    - tqdm
  run_constrained:
    - holoviews >=1.18.0

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: The powerful data exploration & web app framework for Python.
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hoxbro
    - philippjfr
    - ocefpaf
    - maximlt
